// Copies screenshots and generates docs pages from the plugin repo (single sources of truth):
//   ../.wordpress-org/screenshot-*.png -> src/assets/screenshots/ (gitignored copies)
//   ../docs/hooks.md                   -> src/content/docs/docs/developers/hooks.md (committed; kept if the source is absent)
//   ../src/CLI/Command.php docblocks   -> src/content/docs/docs/developers/wp-cli.md
//   ../readme.txt == Changelog ==      -> src/content/docs/docs/changelog.md
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const site = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repo = resolve(site, '..');
const docs = join(site, 'src/content/docs/docs');
const note = (src) => `<!-- Generated by website/scripts/sync.mjs from ${src}. Edit the source, not this file. -->\n\n`;
const write = (file, text) => { mkdirSync(dirname(file), { recursive: true }); writeFileSync(file, text); console.log(`sync: ${file.replace(site + '/', '')}`); };

// Screenshots.
const shotsDir = join(site, 'src/assets/screenshots');
mkdirSync(shotsDir, { recursive: true });
for (const f of readdirSync(join(repo, '.wordpress-org')).filter((f) => /^screenshot-\d+\.png$/.test(f))) {
  copyFileSync(join(repo, '.wordpress-org', f), join(shotsDir, f));
}

// Hooks reference.
const hooksSrc = join(repo, 'docs/hooks.md');
if (existsSync(hooksSrc)) {
  const body = readFileSync(hooksSrc, 'utf8').replace(/^# .*\n+/, '');
  write(join(docs, 'developers/hooks.md'), `---\ntitle: Hooks reference\ndescription: Actions and filters for extending Culprit Finder without touching its code.\n---\n\n${note('docs/hooks.md')}${body}`);
}

// WP-CLI command, from the command class docblocks.
const php = readFileSync(join(repo, 'src/CLI/Command.php'), 'utf8');
const blocks = [...php.matchAll(/\/\*\*([\s\S]*?)\*\/\s*public function (\w+)\(/g)];
let cli = `---\ntitle: WP-CLI command\ndescription: Run and inspect Culprit Finder sessions from the command line with wp culprit-finder.\n---\n\n${note('src/CLI/Command.php')}`;
cli += 'Culprit Finder adds a `wp culprit-finder` command. Run it as an administrator with the global `--user` option, for example `wp --user=admin culprit-finder start`. Commands print JSON unless noted.\n\n';
cli += 'WP-CLI requests are never filtered: the command manages the session, while the browser that holds the session cookie sees the plugins switched off.\n\n';
for (const [, doc, method] of blocks) {
  if (method === '__construct') continue;
  const lines = doc.split('\n').map((l) => l.replace(/^\s*\* ?/, '')).filter((l) => !/^@(param|return|throws)/.test(l));
  const sub = (doc.match(/@subcommand\s+(\S+)/) || [])[1] || method;
  const text = lines.filter((l) => !/^@subcommand/.test(l)).join('\n').trim();
  const [summary, ...rest] = text.split(/\n\n/);
  cli += `## wp culprit-finder ${sub}\n\n${summary.replace(/\n/g, ' ')}\n\n`;
  const restText = rest.join('\n\n').trim();
  if (restText) {
    const out = restText
      .replace(/^## OPTIONS\n/m, '**Options**\n')
      .replace(/^## EXAMPLES\n/m, '**Example**\n')
      .replace(/^---$\n([\s\S]*?)^---$/gm, (_m, inner) => {
        const def = (inner.match(/^default:\s*(.+)$/m) || [])[1];
        const opts = [...inner.matchAll(/^\s+-\s+(.+)$/gm)].map((x) => '`' + x[1].trim() + '`');
        return [def ? `  Default: \`${def.trim()}\`.` : '', opts.length ? `  Accepts: ${opts.join(', ')}.` : ''].filter(Boolean).join('\n');
      })
      .replace(/^\s*(wp .*)$/gm, '```sh\n$1\n```')
      .replace(/^\[(--[^\]]+)\]$/gm, '- `$1` (optional)')
      .replace(/^<([^>]+)>$/gm, '- `<$1>`')
      .replace(/^: /gm, '  ')
      .replace(/\n{3,}/g, '\n\n');
    cli += `${out}\n\n`;
  }
}
write(join(docs, 'developers/wp-cli.md'), cli.replace(/```sh\n```sh\n/g, '```sh\n').replace(/```\n```\n/g, '```\n'));

// Changelog from readme.txt.
const readme = readFileSync(join(repo, 'readme.txt'), 'utf8');
const section = (readme.split(/^== Changelog ==\s*$/m)[1] || '').split(/^== /m)[0].trim();
const changelog = section.replace(/^= (.+) =$/gm, '## $1');
write(join(docs, 'changelog.md'), `---\ntitle: Changelog\ndescription: What changed in each Culprit Finder release.\n---\n\n${note('readme.txt')}${changelog}\n`);
